[workspace]
members = [
    "network_service",
    "transaction_service",
    "block_service",
    "storage_service",
    "consensus_service",
    "overlay_service",
    "validation_service",
    "mining_service",
    "auth_service",
    "alert_service",
    "index_service",
    "shared"
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
