[package]
name = "alert_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.8"
prost = "0.11"
prometheus = "0.13"
tracing = "0.1"
toml = "0.8"
shared = { path = "../shared" }

[build-dependencies]
tonic-build = "0.8"
