name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          override: true
          components: rustfmt, clippy
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip
          unzip protoc-25.1-linux-x86_64.zip -d /usr/local
          sudo chmod +x /usr/local/bin/protoc
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
          echo "PROTOC=/usr/local/bin/protoc" >> $GITHUB_ENV
          protoc --version || { echo "protoc installation failed"; exit 1; }
          which protoc || { echo "protoc not in PATH"; exit 1; }
      - name: Install proto dependencies
        run: |
          mkdir -p protos/google/api
          mkdir -p protos/google/protobuf
          curl -L -o protos/google/api/annotations.proto https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto
          curl -L -o protos/google/api/http.proto https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/http.proto
          curl -L -o protos/google/protobuf/descriptor.proto https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/descriptor.proto
          ls -R protos
      - name: Verify protoc before build
        run: |
          protoc --version || { echo "protoc not accessible"; exit 1; }
          echo "PROTOC is set to: $PROTOC"
      - name: Build
        run: cargo build --release
        env:
          PROTOC: /usr/local/bin/protoc
      - name: Test
        run: cargo test --all
        env:
          PROTOC: /usr/local/bin/protoc
