name: CI

on:
  push:
    branches: [ main, dev ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --release --verbose
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --release --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: target/release/*
        if-no-files-found: warn
